"""Questionnaire outline for the voice-guided CV interview."""

QUESTIONNAIRE = (
    {
        "id": "full_name",
        "title": "Full name",
        "question": "What name would you like to appear at the top of your CV?",
        "goal": "Capture the person's preferred full name for the CV heading.",
        "complete_when": "A usable preferred name is provided.",
        "clarification": "I mean the name you want employers to see at the top of your CV.",
    },
    {
        "id": "professional_title",
        "title": "Professional title",
        "question": "What professional title or type of role best describes you?",
        "goal": "Capture a concise current or target professional title.",
        "complete_when": "A role, occupation, specialty, or target title is provided.",
        "clarification": "For example: software engineer, marketing assistant, or hospitality manager.",
    },
    {
        "id": "contact_details",
        "title": "Contact details",
        "question": "Which contact details and professional links should your CV include?",
        "goal": "Capture any email, phone number, LinkedIn, GitHub, portfolio, or other professional link the user wants included.",
        "complete_when": "At least one desired contact method or link is given, or the user explicitly says to include none.",
        "clarification": "I mean details such as your email or phone number, plus optional links like LinkedIn, GitHub, or a portfolio website.",
    },
    {
        "id": "location",
        "title": "Location",
        "question": "Where are you based, and are you open to remote work or relocation?",
        "goal": "Capture the user's location and any remote-work or relocation preference.",
        "complete_when": "A location or a clear preference about displaying location is provided.",
        "clarification": "You can give a city or country and say whether remote work or relocation interests you.",
    },
    {
        "id": "career_goal",
        "title": "Career goal",
        "question": "What kind of role are you looking for, and what would you like to do next?",
        "goal": "Capture the user's target role and near-term career direction.",
        "complete_when": "A target role, field, responsibility, or career direction is described.",
        "clarification": "Tell me what sort of job, field, or responsibilities you want next.",
    },
    {
        "id": "work_experience",
        "title": "Work experience",
        "question": "Walk me through your most relevant work experience, including employers, roles, and dates.",
        "goal": "Capture relevant employers, roles, responsibilities, and approximate dates.",
        "complete_when": "At least one useful experience is described, or the user explicitly says they have no work experience.",
        "clarification": "You can start with your most recent job and mention the employer, role, dates, and main responsibilities.",
    },
    {
        "id": "achievements",
        "title": "Key achievements",
        "question": "What measurable achievements or moments from your work are you most proud of?",
        "goal": "Capture concrete accomplishments, impact, recognition, or measurable results.",
        "complete_when": "At least one accomplishment is described, or the user explicitly has none to add.",
        "clarification": "Think of a result you improved, a problem you solved, recognition you received, or something successful you delivered.",
    },
    {
        "id": "education",
        "title": "Education",
        "question": "Tell me about your education, including qualifications, institutions, and dates.",
        "goal": "Capture qualifications, fields of study, institutions, and dates where known.",
        "complete_when": "At least one education or training item is described, or the user explicitly has none to add.",
        "clarification": "Mention a degree, diploma, school, university, apprenticeship, or other relevant training.",
    },
    {
        "id": "skills",
        "title": "Skills",
        "question": "Which technical, practical, and interpersonal skills should stand out on your CV?",
        "goal": "Capture job-relevant technical, practical, and interpersonal skills.",
        "complete_when": "At least one usable skill is provided.",
        "clarification": "Examples include software or tools you use, practical abilities, communication, teamwork, or leadership.",
    },
    {
        "id": "projects",
        "title": "Projects",
        "question": "Which projects best show what you can do, and what was your contribution?",
        "goal": "Capture relevant projects, the user's contribution, and useful outcomes or technologies.",
        "complete_when": "At least one project is described, or the user explicitly has no project to include.",
        "clarification": "This can be a work, school, personal, volunteer, or open-source project. Tell me what you built or contributed.",
    },
    {
        "id": "certifications_languages",
        "title": "Certifications and languages",
        "question": "Do you have any relevant certifications, courses, awards, or language skills?",
        "goal": "Capture relevant certifications, courses, awards, and spoken languages.",
        "complete_when": "At least one item is supplied, or the user explicitly says there are none.",
        "clarification": "You can mention professional certificates, short courses, awards, or languages you speak.",
    },
    {
        "id": "additional_information",
        "title": "Additional information",
        "question": "Is there anything else you want an employer to know about you?",
        "goal": "Capture any remaining CV-relevant information the user wants included.",
        "complete_when": "The user provides additional information or explicitly says there is nothing else.",
        "clarification": "This could include volunteering, interests, availability, work authorization, or anything important we missed.",
    },
)


QUESTION_BY_ID = {item["id"]: item for item in QUESTIONNAIRE}
